runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /weather
  script: main.app
  # login: admin

# - url: .*
#   script: site.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
